export const BUILDING_POOLS = {
  Common: [
    "Apiary",
    "Bakery",
    "Ballistas",
    "Barn",
    "Basic Shrine",
    "Beast Pens",
    "Blacksmith",
    "Butcher",
    "Cider Press",
    "Crystal Upgrade",
    "Farmlands",
    "Fishery",
    "Gardens",
    "General Store",
    "Grain Silo",
    "Graveyard",
    "Housing: Commoner",
    "Inn",
    "Lumber Mill",
    "Mill",
    "Mine",
    "Quarry",
    "Smokehouse",
    "Stables",
    "Tailor",
    "Tavern",
    "Tool Shed",
    "Town Guard Post",
    "Vendor",
    "Water Trough",
    "Well",
    "Wooden Wall",
    "Woodcutter's Hut"
  ],

  Uncommon: [
    "Alchemist",
    "Barracks",
    "Brewery",
    "Carpenter Shop",
    "Clocktower",
    "Community Oven",
    "Crystal Upgrade",
    "Distillery",
    "Dock",
    "Grove",
    "Guard Tower",
    "Hardwood Walls",
    "Housing: Comfortable",
    "Immigration Center",
    "Jewelry Shop",
    "Library",
    "Market Square",
    "Mason's Workshop",
    "Pond",
    "Post Office",
    "Ropeworks",
    "School",
    "Tannery",
    "Town Hall",
    "Trade Post",
    "Trebuchets",
    "Warehouse",
    "Weaver's Hall"
  ],

  Rare: [
    "Amphitheater",
    "Apothecary",
    "Aqueduct System",
    "Armory",
    "Bank",
    "Bathhouse",
    "Courthouse",
    "Crystal Upgrade",
    "Workshop Quarter",
    "Embassy Annex",
    "Engineers' Guild",
    "Explosive Ballistas",
    "Guildhall",
    "Herbal Greenhouse",
    "Hospital",
    "Housing: Wealthy",
    "Lighthouse",
    "Mint",
    "Observatory",
    "Oracle",
    "Printing Press",
    "Prison",
    "Red Light District",
    "Stone Walls",
    "Training Grounds",
    "University"
  ],

  Epic: [
    "Adventurers' Guildhall",
    "Airship Dockyard",
    "Artifact Vault",
    "Cannons",
    "Caravan Outpost",
    "Castle",
    "Communications Core",
    "Crystal Upgrade",
    "Fey Crossing",
    "Foreign Affairs Ministry",
    "Grand Shrine",
    "Housing: Noble",
    "Illusion Field Generator",
    "Mirage Citadel",
    "Monster Arena",
    "Monster Capture Field",
    "Planar Beach",
    "Reinforced Stone Walls",
    "Relic Sanctum",
    "Skyharbor",
    "Steam Factory",
    "Temple",
    "Torture Chambers",
    "Wall/Fortifications"
  ],

  Legendary: [
    "Arcana Tower",
    "Arcane Walls",
    "Captain's Quarters",
    "Crystal Upgrade",
    "Deathless Grounds",
    "Doomsday Cannon",
    "Dragonforge",
    "Dreamweaver",
    "Elemental Cannons",
    "Elemental Shipmaker",
    "Enchanted Forest",
    "Housing: Royal",
    "Mortality Limiter Remover",
    "Planar Anchor",
    "Planar Escape Pods",
    "Planar Tentacles",
    "Raestorum Center",
    "School of Driftum",
    "Shield Generator",
    "Techcrafter",
    "The Seeker",
    "War Academy Supreme"
  ],

  Beyond: [
    "Heart of Kosmos",
    "Universal Portal",
    "Lylandra's Residence",
    "New Drift Seed",
    "Dungeon of the Endless",
    "The Ark",
    "The Maker's Creatorium",
    "The First Last Tower of Chronomancy"
  ]
};
