export const BUILDING_POOLS = {
  Common: [
    "Farmlands",
    "Pond",
    "Gardens",
    "Grove",
    "Graveyard",
    "Housing: Commoner",
    "Vendor Stall",
    "Tailor Shop",
    "Blacksmith Forge",
    "Stables",
    "Beast Pens",
    "Lumber Yard",
    "Fishery",
    "Mine",
    "Quarry",
    "Tavern",
    "Inn",
    "Town Guard Post",
    "Well",
    "Bakery",
    "Barn",
    "Tool Shed",
    "Butcher",
    "Smokehouse",
    "Stone Mason",
    "Clay Pit",
    "Carpenter Shed",
    "Roadworks Depot",
    "Watch Post",
    "Crystal Upgrade"
  ],
  Uncommon: [
    "Post Office",
    "Clocktower",
    "Town Hall",
    "Immigration Center",
    "Market Square",
    "Jewelry Shop",
    "Mill",
    "Warehouse",
    "Dock",
    "Distillery",
    "Brewery",
    "Library",
    "School",
    "Alchemist Lab",
    "Carpenter Workshop",
    "General Store",
    "Grain Silo",
    "Community Oven",
    "Trade Post",
    "Messenger Guild",
    "Surveyor Office",
    "Harbor Office",
    "Bank",
    "Stone Warehouse",
    "Merchant Guild",
    "Crystal Upgrade"
  ],
  Rare: [
    "Hospital",
    "Bathhouse",
    "University",
    "Armory",
    "Barracks",
    "Training Grounds",
    "Amphitheater",
    "Entertainment District",
    "Apothecary",
    "Aqueduct System",
    "Lighthouse",
    "Printing Press",
    "Oracle Chamber",
    "Observatory",
    "Courthouse",
    "Guildhall",
    "Guard Tower",
    "Herbal Greenhouse",
    "Embassy Annex",
    "Mint",
    "Trade Exchange",
    "Military Academy",
    "Engineering Hall",
    "Crystal Upgrade"
  ],
  Epic: [
    "Foreign Affairs Ministry",
    "Housing: Noble Estate",
    "Illusion Field Generator",
    "Interrogation Chambers",
    "City Walls",
    "Caravan Outpost",
    "Planar Beach",
    "Fey Crossing",
    "Airship Dockyard",
    "Artifact Vault",
    "Monster Arena",
    "Adventurers Guildhall",
    "Monster Capture Field",
    "Castle",
    "Temple",
    "Mirage Citadel",
    "Skyharbor",
    "Relic Sanctum",
    "Grand Shrine",
    "Arcane Power Plant",
    "Dimensional Gate",
    "War Council Hall",
    "Crystal Upgrade"
  ],
  Legendary: [
    "School of Driftum",
    "Arcana Tower",
    "Communications Core",
    "Steam Factory",
    "Elemental Shipmaker",
    "Enchanted Forest",
    "Techcrafter",
    "The Seeker",
    "Planar Tentacles",
    "Planar Anchor",
    "Planar Escape Pods",
    "Shield Generator",
    "Raestorum Center",
    "Dreamweaver",
    "Deathless Grounds",
    "Doomsday Cannon",
    "Dragonforge",
    "Mortality Limiter Remover",
    "Captain's Quarters",
    "Reality Engine",
    "Chronomancy Lab",
    "World Archive",
    "Crystal Upgrade"
  ],
  Beyond: [
    "Lylandra's Residence",
    "Universal Portal",
    "Dungeon of the Endless",
    "Heart of Kosmos",
    "The Maker's Creatorium",
    "The First Last Tower of Chronomancy",
    "Ark",
    "New Drift",
    "Cosmic Foundry",
    "Eternal Garden"
  ]
};
